microsoft/icu

build/nuget/Microsoft.icu.icu4c.win.targets, build/nuget/SignConfig-ICU-Binaries.xml, build/nuget/SignConfig-ICU-Nuget.xml, build/nuget/Template-Microsoft.icu.icu4c.win.nuspec, build/scripts/Create-Nuget.ps1
This PR adds a code signing config for ARM64 and changes the naming of the Nuget slightly.
=> Add code signing config for ARM64, change the naming of the Nuget

changelog.md, version.txt
This is related to PR #8.
This PR updates the `changelog.md` file for the Taiwan calendar changes, and bumps the MS-ICU version number to `67.1.0.2`, in order to prepare for a new release.
Note: Once this PR is merged I'll need to use a merge commit to merge this change to the `maint/maint-67` branch, as the changes for PR #8 were accidentally merged using a merge commit instead of a squash commit -- meaning that it can't be cleanly cherry-picked into the maint branch.
=> Update changelog for Taiwan calendar changes, and bump version to 67.1.0.2

changelog.md, version.txt
This is related to PR #13 .
This PR updates the `changelog.md` file for the Taiwan calendar changes, and bumps the MS-ICU version number to `64.2.0.2`, in order to prepare for a new release.
=> Update changelog for Taiwan calendar changes, and bump version to 64.2.0.2

icu-patches/patches/012-MSFT-Patch-StaticLink_VCRuntime_VCStartup_STL_but_DynamicLink_UCRT.patch, icu-patches/readme.md, icu/icu4c/source/common/common.vcxproj, icu/icu4c/source/i18n/i18n.vcxproj
This PR modifies the vcxproj files for the "common" (uc) and "i18n" (in) libraries in order to statically link the VCRuntime (`libvcruntime.lib`), VCStartup (`libcmt.lib`), and STL/MSVCP (`libcpmt.lib`), but dynamically link the UCRT (`ucrt.lib`).
This PR also adds a new MSFT-Patch file to the `icu-patches` folder in order to retain this change for future versions of ICU. (I also reworded the `readme.md` file a bit for the patches folder).
The UCRT (`ucrtbase.dll`) is included as Windows OS component in Windows 10 and above. (See https://docs.microsoft.com/cpp/c-runtime-library/crt-library-features). On previous versions of Windows it is available via a Windows Update package. (See the KB article here: https://support.microsoft.com/kb/2999226).
However, the `vcruntime*.dll` and …
=> Statically link the VCRuntime, VCStartup, and STL, but dynamically link to the UCRT.

build/azure-nuget.yml, build/nuget/Template-runtime-meta.nuspec, build/scripts/Create-Nuget-Runtime.ps1
This PR completely converts the Nuget build pipeline configuration from the ADO "classic" configuration into a YML/YAML file, which can be checked in to the repository.
Previously the Nuget build pipeline configuration only existed on MSCodeHub, meaning that nobody else could make any changes to it. This meant that in order to (for example) add support for a new platform to the Nuget package, changes would need to be done *manually* by someone on our team to the ADO pipeline setup within MSCodeHub.
With this change, anyone can create a PR to propose changes to add support for a new platform, etc. to the Nuget package pipeline.
This change also fixes the casing on the Nuget name to be "`Microsoft.ICU.ICU4C.Runtime`".
=> Convert the Nuget build pipeline to YAML, and check it in to the repo

build/azure-pipelines.yml, build/scripts/Set-ICUVersion.ps1, icu/icu4c/source/common/unicode/uvernum.h, version.txt
When testing out the Nuget package, @safern noticed that the value reported by the API `u_getVersion` doesn't actually match the MS-ICU version number. This is because the macro `U_ICU_VERSION` wasn't updated, only the macro `U_ICU_VERSION_BUILDLEVEL_NUM` was being updated. (Thanks @safern!)
I was going to modify the `Set-ICUVersion.ps1` script to set this macro as well at build time.
However, when testing I noticed that the `make dist` command actually takes the output from the git commit using the `git archive` command. This means that we need to actually modify and commit the version number, and not set it on the fly during the build.
Instead, we'll now have to update the two macros in the `uvernum.h` file directly, but in order to make sure things don't get out of sync, I modified the …
=> Fix setting the MS-ICU version number in the uvernum.h file, and don't set it at build time.

build/azure-nuget.yml, build/nuget/SignConfig-ICU-Binaries-runtime.xml, build/nuget/SignConfig-ICU-Nuget.xml, build/nuget/Template-runtime-meta.nuspec, build/nuget/Template-runtime-rid.nuspec, build/scripts/Create-Nuget-Runtime.ps1
This change modifies the Nuget build pipeline to enable building Nuget Symbol packages for the Windows binaries.
These symbol packages (`*.snupkg`) contain the PDB files that are necessary for debugging. They are separate from the main package in order to reduce the size/bloat of the "runtime" package. Nuget.org has special support for resolving symbols by pulling these "symbol" packages, so this allows a clean separation between the DLLs and the PDBs. (Meaning you don't download the PDBs by default unless you need them).
This change also modifies the build pipeline to add more diagnostic output (which is useful for debugging build issues), and explicit "clean" steps to ensure that each stage doesn't have leftover artifacts from previous runs.
=> Produce Nuget Symbol Packages for debugging, and add some more diagnostics to pipeline

changelog.md, icu/icu4c/source/common/unicode/uvernum.h, version.txt
This bumps the version number to 67.1.0.3, and updates the changelog.
=> Bump the version number to 67.1.0.3, and update the changelog.

build/nuget/SignConfig-ICU-Nuget.xml, build/scripts/Create-Nuget-Runtime.ps1, changelog.md, icu/icu4c/source/common/unicode/uvernum.h, version.txt
It turns out that Nuget.org won't accept any packages that start with a `runtime*` prefix. So we'll need to move the Runtime ID (RID) to the end of the Nuget package name for the dependent runtime packages instead.
This change also bumps the version number, as Nuget.org won't let you re-submit a package with the same version once it has been removed/deleted.
=> Fix the naming of the dependent Runtime Nuget packages.

build/scripts/Set-ICUVersion.ps1, icu-patches/patches/013-MSFT-Patch-ICU_Add_version_number_to_PDB_names.patch, icu/icu4c/source/common/common.vcxproj, icu/icu4c/source/i18n/i18n.vcxproj, icu/icu4c/source/stubdata/stubdata.vcxproj
It turns out that Nuget.org won't accept any symbols packages unless the PDB filenames exactly match the filenames for the DLLs.
By default, the Windows VS builds for ICU don’t include the version number on the PDB file name (ex: `icuuc.pdb` vs `icuuc67.dll`), so this means that Nuget.org rejects them. This change creates a new MSFT patch to add the version number to the PDB filename.
This change also fixes the `ICUVersion` environment variable in the Power Shell script `Set-ICUVersion.ps1`.
We need to set/change the environment variable for the current PowerShell session as well, as the script can be called by other scripts.
=> Add the ICU Major version number to the PDB filename, fix ICUVersion variable

build/azure-nuget.yml, build/dockerfiles/centos/Dockerfile, build/nuget/SignConfig-ICU-Nuget.xml, build/scripts/Create-Nuget-Runtime.ps1, build/scripts/build-icu.sh
This change enables building Linux x64 runtime packages for the MS-ICU Nuget package in the build pipeline.
The binaries produced link to `glibc`, so they should work on any Linux distribution that uses the `glibc` standard library. (Note: This means that they won't work on distros like Alpine, which use `musl` as the standard library. Adding support for `musl` is out-of-scope for this PR).
In order to produce these binaries, we actually build inside a Docker container, and then extract the output from that, and then package it up in the Nuget package.
To do this we use the special CentOS7 Docker image to build, which is the same as the one used for dotnet. This image has a number of updates applied and tools preinstalled, and also uses a much newer version of the Clang compiler (Clang 9) …
=> Enable building Linux x64 Nuget runtime package

changelog.md, icu/icu4c/source/common/unicode/uvernum.h, version.txt
This change bumps the version number to 67.1.0.5, and updates the changelog to add notes about the included changes/fixes.
=> Bump the version number to 67.1.0.5, and update the changelog.

build/azure-nuget.yml, build/dockerfiles/centos/Dockerfile, build/nuget/SignConfig-ICU-Nuget.xml, build/scripts/Create-Nuget-Runtime.ps1, build/scripts/Set-ICUVersion.ps1, build/scripts/build-icu.sh, changelog.md, icu-patches/patches/013-MSFT-Patch-ICU_Add_version_number_to_PDB_names.patch, icu/icu4c/source/common/common.vcxproj, icu/icu4c/source/common/unicode/uvernum.h, icu/icu4c/source/i18n/i18n.vcxproj, icu/icu4c/source/stubdata/stubdata.vcxproj, version.txt
This updates the `maint/maint-67` branch to `67.1.0.5`.
(This will be done as a merge commit to keep the history).
Note: Once this is merged the MSCodeHub submodule can be updated. :)
=> Update maint/maint-67 to 67.1.0.5

build/azure-nuget.yml, build/scripts/build-icu.sh
This change enables the creation of debugging symbols for the Linux x64 binaries that are part of the MS-ICU Nuget package.
In order to produce the debugging symbols for the Linux ELF binaries, we need to build the ICU library code with symbols support (ie: the `-g` compiler option).
We want to produce debugging symbols for "release" builds, but we don't want to use the `--enable-debug` flag/option with the `runConfigureICU` script, as that will turn on all kinds of debug code and asserts inside the ICU library code.
Instead we set the environment variables `CFLAGS` and `CXXFLAGS` (which are used by the compiler) to add the `-g` option. This lets us to do a full "release" build but still have symbols.
Debugging symbols are handled differently on Linux than Windows, and the debug symbols …
=> Produce debugging symbols for the Linux x64 binaries

build/azure-nuget.yml
This change modifies the Nuget build pipeline to publish the debugging symbols for the Window pre-built binaries to the public Microsoft symbol server. This also moves the publishing step to be *after* the code signing steps, in case they might fail. (If they fail we don't want to publish the symbols).
This means that the symbols for the pre-built Windows binaries in the Nuget package can now be pulled from the public symbol server URLs:
- `https://msdl.microsoft.com/download/symbols` (external)
- `http://symweb` (internal)
Note: The authorization for this publishing step is based on the _individual user_ that manually triggers runs the pipeline run.
This means that we don't need to use a special service account or setup Azure Key vault storage for a custom PAT token.
Since we can use the …
=> Publish Windows debugging symbols for MS-ICU Nuget to the public Microsoft symbol server

build/scripts/Set-ICUVersion.ps1, changelog.md, icu/icu4c/source/common/unicode/uvernum.h, version.txt
This change updates the version number `67.1.0.6` and the changelog.md file
This also makes the output from the `Set-ICUVersion.ps1` script more helpful if
the version number doesn't match.
Note: Once this is merged, I plan on creating a merge into the `maint/maint-67` branch,
and then pushing out a new Nuget package version and GitHub release.
=> Bump the version number to 67.1.0.6, and update changelog.md

build/azure-nuget.yml, build/nuget/Template-runtime-meta.nuspec, build/scripts/Create-Nuget-Runtime.ps1, build/scripts/Set-ICUVersion.ps1, build/scripts/build-icu.sh, changelog.md, icu/icu4c/source/common/unicode/uvernum.h, version.txt
This updates the `maint/maint-67` branch to `67.1.0.6`.
(This will be done as a merge commit to keep the history).
Note: Once this is merged, I plan on creating a new GitHub release, and then pushing out a new Nuget package.
=> Update maint/maint-67 to 67.1.0.6

build/nuget/SignConfig-ICU-Nuget.xml
I missed this when removing the Nuget symbol packages. It causes warnings/errors during the Nuget code-sign build step, which causes the build to fail. 
I'll need to merge this into the `maint/maint-67` branch as well.
=> Remove Nuget symbol packages from Code Sign config file

build/nuget/SignConfig-ICU-Nuget.xml
Need to pick up the fix for the Nuget code sign config file (#35) in the `maint/maint-67` branch.
=> Update maint/maint-67 to pick up fix for Nuget code-sign config file

build/azure-nuget.yml, build/azure-pipelines.yml, build/scripts/Create-Nuget-Runtime.ps1
This PR modifies the names of the published build artifacts slightly, in order to reduce the amount of manual renaming that is needed when creating a new Release on GitHub and Nuget.org.
=> Reduce manual renaming of things need for new Releases

icu/tools/cldr/cldr-to-icu/pom.xml
The new Component Governance task flagged Apache Ant as being out of date. The Apache Ant is only used as a build time dependency though, and only for the CLDR->ICU data conversion process -- so to be honest it doesn't really matter all that much for MS-ICU releases. However, since this is flagged as a security issue, we need to fix it by updating Ant to a newer version.
(Note: This will need to be cherry-picked into the maint-67 branch as well.)
=> Update Apache Ant to 1.10.9

build/azure-nuget.yml
It seems the Component Governance task format has changed slightly, and the new format is required for Package ES code signing. This PR updates the format to use the new style.
(Note: This will need to be cherry-picked into the maint-67 branch as well.)
=> Update the Component Governance task to use the new format.

build/azure-nuget.yml, icu/tools/cldr/cldr-to-icu/pom.xml
This change cherry-picks the two changes from PR #38 and PR #39 into the `maint/maint-67` branch.
Changes:
- Update the Component Governance task to use the new format.
- Update Apache Ant to 1.10.9
=> Cherry-pick Component Governance task update and Apache Ant update to maint/maint-67

build/azure-nuget.yml
Thanks to @huichen123 for noticing this. We were actually publishing to the Microsoft internal server for symbols instead of the public one.
Note: I'll need to cherry-pick this change over to the `maint/maint-67` branch once I've tested that pipeline can actually publish correctly.
=> Update symbols publishing to use the public server instead of the internal one

build/azure-nuget.yml
Note: This is a cherry-pick into the `maint/maint-67` branch from PR #41.
This updates the PDB symbols publishing to use the public server instead of the internal one.
(Thanks to @huichen123 for noticing this. We were actually publishing to the Microsoft internal server for symbols instead of the public one.)
=> Cherry-pick PDB Symbols publishing change into maint/maint-67 branch

changelog.md, version.txt
This PR updates the `changelog.md` file and bumps the MS-ICU version number to `64.2.0.3`, in order to prepare for a new release.
=> Update maint/maint-64 to 64.2.0.3

changelog.md, icu/icu4c/source/common/unicode/uvernum.h, version.txt
This change updates the version number `67.1.0.7` and the `changelog.md` file
Note: Once this is merged, I plan on creating a merge into the `maint/maint-67` branch,
and then pushing out a new Nuget package version and GitHub release.
=> Bump the version number to 67.1.0.7, and update changelog.md

icu/tools/cldr/.gitignore, icu/tools/cldr/lib/install-cldr-jars.sh, icu/tools/cldr/lib/pom.xml
This is part 3 of N for updating to ICU 68.1.
It's generally considered a bad practice or an anti-pattern to have files checked-into a git repo which are at the same time also excluded by `.gitignore` file(s) in the repo as well.
These two files are used/needed by the CLDR-to-ICU data build process.
However, I accidentally removed them in the previous commit/PR, as there is a checked-in `.gitignore` file which excludes them. (This means when coping from one repo/clone to another repo/clone the files won't get added.)
This commit adds them back, and also add an exclusion to the `.gitignore` file so that they don't get ignored.
I filed an upstream ICU ticket for this here as well:
https://unicode-org.atlassian.net/browse/ICU-21427
Note: The CI builds for this PR will fail and that is …
=> [ICU 68.1 Update] The "tools/cldr/.gitignore" shouldn't ignore already checked-in files.

build/azure-nuget.yml, build/azure-pipelines.yml, icu/icu4c/source/common/unicode/uvernum.h, version.txt
This is part 5 of N for updating to ICU 68.1.
This change updates the Azure CI configuration files to use VS 2019 (from VS 2017) for the build validation and the Nuget package. With this change the CI builds for MS-ICU should now be working and passing again.
This change also updates the MS-ICU version number to 68.1.0.1, since we have now diverged from the upstream unmodified source code, as we've now applied the MSFT patches in the previous change.
=> [ICU 68.1 Update] Update Azure Nuget CI build to use VS2019

icu-patches/patches/014-MSFT-Patch-CLDR_to_ICU_data_tool_Windows_changes_part2.patch, icu-patches/readme.md, icu/tools/cldr/cldr-to-icu/build-icu-data.xml
This is part 6 of N for updating to ICU 68.1.
This change modifies/patches the CLDR-to-ICU data build tool so that it now actually works on Windows.
This took an inordinate amount of time to track down and figure out what was going wrong...
The CLDR-to-ICU data build process added a new additional "convert" exec target to the Maven build file in ICU 68.1:
https://github.com/microsoft/icu/commit/c8d5a7cbe2c1cdc3bbe13d670df1e2ad5bff7d27#diff-9453860ff1b33b84a7384219248361d667fe1d0dc13d93e28a7c8381313d6e53
However, it turns out that some of the variables that are passed to Apache ANT have embedded spaces or periods in them. This causes the JVM to throw a `java.lang.IllegalArgumentException` error before ANT even starts up, as it doesn't allow/permit JVM variables (ie: ones that start with …
=> [ICU 68.1 Update] Patch CLDR-to-ICU data tool for Windows (Part 2)

icu-patches/patches/015-MSFT-Patch-ICU_Header_changes_for_Windows_part3.patch, icu/icu4c/source/common/unicode/uloc.h, icu/icu4c/source/i18n/unicode/unumberrangeformatter.h
This is part 8 of N for updating to ICU 68.1.
The Windows SDK header tool script relies on the `#endif` containing the name of opening macro in the `#if` statement, in order to match them up. It turns out that these two don't have comments on the closing endif, likely because the opening if statement is only 2-3 lines above it. This change adds the comment to closing tag in order to unbreak the header tool scripts.
This change also adds a MSFT-Patch file for the change as well.
=> [ICU 68.1 Update] Add comments to closing endifs for Windows SDK Header tool script

build/azure-nuget.yml
This is part 9 of N for updating to ICU 68.1.
This is a relatively minor change. I noticed that the ARM builds are now taking a bit longer, causing the CI build to occasionally timeout and require triggering a re-run. This change simply increases the timeout amount on the build CI config to allow more time for the ARM builds to finish.
=> [ICU 68.1 Update] Increase the build timeout for CI-Nuget builds

icu/icu4c/source/data/coll/aa.txt, icu/icu4c/source/data/coll/cu.txt, icu/icu4c/source/data/coll/nso.txt, icu/icu4c/source/data/coll/ssy.txt, icu/icu4c/source/data/coll/st.txt, icu/icu4c/source/data/coll/tn.txt, icu/icu4c/source/data/coll/vo.txt, icu/tools/cldr/cldr-to-icu/build-icu-data.xml
This is part 11 of N for updating to ICU 68.1.
For the extra locales that we pull in from CLDR Seed (for parity with NLS, etc). we also want to pull in their data for annotations, casing, collation, rbnf, and transforms as well.
This change rebuilds the ICU data using the rebuilt CLDR-MS data from MSCodeHub.
See PR: https://mscodehub.visualstudio.com/OSS_github.com_Unicode-org/_git/ms-icu/pullrequest/13846
This change adds the collation data for the 5 seed locales (aa, nso, ssy, st, tn). which have data.
Note: I'm not going to list the other locales in the `build-icu-data.xml` file, as they don't have any data, and doing so makes the data build tool generated empty/stub files for them, which I don't think we want.
For these new collations, we'll need to add the seed locales to the …
=> [ICU 68.1 Update] Rebuild data using extra data from CLDR seed locales

build/azure-nuget.yml
This PR removes the Nuget signing check from the CI pipeline, as the CertificateFingerprint can change over time.
Having a hard-coded signature wasn't super useful anyways, as the Nuget.org site already validates that packages are signed when they are uploaded.
=> Remove Nuget signing check from CI pipeline, as the CertificateFingerprint can change.

changelog.md, icu/icu4c/source/common/cmemory.h, icu/icu4c/source/common/uloc_tag.cpp, icu/tools/cldr/.gitignore
This PR cherry-picks two tickets from the upstream ICU repo that were merged after the ICU 68.2 release.
- ICU-21427 Don't ignore already checked-in files under "tools/cldr/lib"
- ICU-21118 check that dst and src are not null in uprv_memcpy
The first one I had already done with https://github.com/microsoft/icu/pull/52, so this is mostly just making an update for the comments and to record it in the `changelog.md` file.
The second one was fixed by @erik0686, and prevents undefined behavior in `ultag_parse`.
=> Cherry-pick 2 tickets after the ICU 68.2 release

icu/icu4c/source/common/wintz.cpp
This change cherry-picks the upstream fix for the issue of the Windows Time Zone offset being wrong when Automatic DST setting is OFF in the Control Panel.
ICU-21465 Windows Time Zone offset is wrong when Automatic DST setting is OFF
https://unicode-org.atlassian.net/browse/ICU-21465
Upstream PR into `master` is here: https://github.com/unicode-org/icu/pull/1465
Upstream PR into `maint/maint-68` is here: https://github.com/unicode-org/icu/pull/1543
**From the upstream PR description:**
This fixes a bug in the changes for ICU-13845, for handling when the "Automatic DST" setting is OFF in the Control Panel.
It turns out that the offset value for the calculated time zone when the "Automatic DST" setting is turn off is wrong. The sign for the time zone offset is flipped. …
=> Cherry-pick: Fix Windows TZ offset when Automatic DST setting is OFF

icu/icu4c/source/common/uresbund.cpp, icu/icu4c/source/test/cintltst/cloctst.c, icu/icu4c/source/test/cintltst/cloctst.h
This change cherry-picks the upstream fix for the issue of an infinite loop when calling various APIs with locale IDs that contain `RES_PATH_SEPARATOR`.
https://unicode-org.atlassian.net/browse/ICU-21449
Upstream PR:
https://github.com/unicode-org/icu/pull/1549
**From the upstream PR:**
When calling APIs like `uloc_getDisplayLanguage`, if the input locale ID has `/` (the `RES_PATH_SEPARATOR` value) then the resource look-up code ends up in an infinite loop.
For example, the following code will never return:
```c++
UErrorCode status = U_ZERO_ERROR;
const char* localeNameTemp = "/"; // RES_PATH_SEPARATOR
uloc_getDisplayLanguage(localeNameTemp, localeNameTemp, NULL, 0, &status);
```
The `do {...} while` loop in `ures_getByKeyWithFallback` calls `res_findResource`, but it …
=> Cherry-pick: ICU-21449 Infinite loop can occur with locale IDs containing RES_PATH_SEPARATOR

changelog.md, icu/icu4c/source/common/unicode/uvernum.h, version.txt
This change updates the version number `68.2.0.2` and the `changelog.md` file, as we've cherry-picked two fixes from upstream ICU.
Note: Once this is merged, I plan on creating a merge into the `maint/maint-68` branch, and then updating the MSCodeHub to pull in the new version.
=> Bump version number to 68.2.0.1, and update changelog.md

changelog.md
It turns out that I used the wrong link for the Windows Time Zone cherry-pick, in the `changelog.md` file and PR #65 description. (The link used was for another Windows TZ issue I fixed that was already included in ICU 68.2.)
It should be https://github.com/unicode-org/icu/pull/1539 instead.
(Thanks to @daniel-ju for catching this!)
Note: I edited the PR description in #65, but I can't force-push to fix the actual commit itself, so it will have to stay as-is.
=> Fix the PR link for the Windows TZ cherry-pick in the changelog.md file

build/azure-nuget.yml, build/dockerfiles/ubuntu-arm64/Dockerfile, build/scripts/build-icu-arm64.sh, build/scripts/build-icu-x64.sh
This adds support for creating pre-built binaries for Linux ARM64, for use in the MS-ICU Nuget package.
This change adds support for building pre-built binaries for Linux ARM64, for use in the MS-ICU Nuget package.
The binaries are cross-compiled inside of a Docker container, extracted, published as intermediate artifacts, and then packaged up into a Nuget package in the build pipeline, and finally published again.
The container used is from the .NET Core build tools, from https://github.com/dotnet/dotnet-buildtools-prereqs-docker
The shared libraries are built for the "`aarch64-linux-gnu`" target platform using the same base OS (Ubuntu 16.04 (xenial)) and CrossRoot FileSystem that is used for building the .NET Core Linux ARM64 binaries. This means they should work together without issue, …
=> Add support for pre-built Linux ARM64 binaries for the MS-ICU Nuget.

changelog.md, icu/icu4c/source/i18n/regexcmp.cpp, icu/icu4c/source/test/testdata/regextst.txt
This change cherry-picks the upstream fix for the Regex assertion failure with nested look-behind blocks.
https://unicode-org.atlassian.net/browse/ICU-21492
=> Cherry-pick: ICU-21492 Fix regex compile assertion failure.

changelog.md, icu/icu4c/source/common/uchar.cpp, icu/icu4c/source/common/uprops.h
This change cherry-picks the upstream fix to remove macros that use names which are reserved by the C++ standard.
There are upcoming changes to the MSVC STL headers which might use some of these reserved names, which causes conflicts.
https://unicode-org.atlassian.net/browse/ICU-21461
=> Cherry-pick: ICU-21461 uprops.h: remove unused gc macros

changelog.md, icu/icu4c/source/common/locid.cpp
`uprv_strcmp` is an alias for `strcmp`, which returns an `int`. On some platforms (such as aarch64 or arm64-v8a) it may return positive values that are larger than 127, which will cause the resulting value to be *negative* when cast to an `int8_t`.
https://unicode-org.atlassian.net/browse/ICU-21521
Note: The upstream change modifies the file locid.cpp in 3 places. However, in the ICU v68.2 code the change is only needed in 2 places, as the `tfields` code was added in ICU v69.
=> Cherry-pick: ICU-21461 Fix cast of uprv_strcmp

changelog.md, icu/icu4c/source/common/unicode/uvernum.h, version.txt
This change updates the version number `68.2.0.3` and the `changelog.md` file.
Note: Once this is merged, I plan to create a merge into the `maint/maint-68` branch, and then update the MSCodeHub repo to pull in the new version.
=> Bump the version number to 68.2.0.3, and update changelog.md

changelog.md
This updates the changelog.md to add note about pre-built Linux ARM64 Nuget.
(I forgot to add this to the changelog when I did the work in the other PR).
=> Update changelog.md to add note about pre-built Linux ARM64 Nuget

changelog.md
The original change in PR #74 had the wrong ICU ticket number in the changelog.md, it should have been ticket `ICU-21521` instead.
Thanks to @daniel-ju for catching this!
=> Fix ICU ticket number in changelog.md

icu/icu4c/source/common/locid.cpp, icu/icu4c/source/test/intltest/collationtest.cpp
This change cherry-picks an upstream fix for an invalid free of a long locale name.
Upstream ticket: https://unicode-org.atlassian.net/browse/ICU-21537
Upstream PR: https://github.com/unicode-org/icu/pull/1656
=> Cherry-pick: ICU-21537 Fix invalid free by long locale name

changelog.md, icu/icu4c/source/common/unicode/uvernum.h, version.txt
This change bumps the version number to 68.2.0.4.
Note: Once this is merged, I'll update the `maint-68` branch along with the MSCodeHub repo to pull in the updated `maint-68` branch.
=> Bump version number to 68.2.0.4

icu-patches/patches/016-MSFT-Patch-Bump_guava_version_to_30.0-jre.patch, icu/tools/cldr/cldr-to-icu/pom.xml
Bumped the guava version from 29.0-jre to 30.0-jre to pass the Component Governance task in the CI build.
Added a patch file as well in case this isn't updated in upstream ICU.
=> Bump guava version to 30.0-jre

changelog.md, icu/icu4c/source/common/unicode/uvernum.h, version.txt
This change bumps the version to 68.2.0.5, and updates the changelog.md file
=> Bump version number to 68.2.0.5, and update changelog.md

icu/icu4c/source/common/locid.cpp, icu/icu4c/source/test/intltest/loctest.cpp, icu/icu4c/source/test/intltest/loctest.h
This change cherry-picks the upstream fix in locid.cpp and the additional test cases.
Upstream ticket: https://unicode-org.atlassian.net/browse/ICU-21587
Upstream PR: https://github.com/unicode-org/icu/pull/1698
Original PR description:
> Edge cases not fixed in assign and move assign operator
> while the locale is long and call setKeywordValue with incorrect
> keyword/values.
=> Cherry-pick: ICU-21587 Fix memory bug w/ baseName

build/azure-pipelines.yml
This PR adds the necessary steps to run Valgrind on PR's made to this repo. 
Worth mentioning that unlike upstream ICU, where valgrind is run on batches of PR's, we will run it for every PR made here :)
=> Add Valgrind build and test to CI pipeline

changelog.md, icu/icu4c/source/common/unicode/uvernum.h, version.txt
This change bumps the version to 68.2.0.6, and updates the `changelog.md` file
=> Bump version number to 68.2.0.6, and update changelog.md

build/azure-nuget.yml
Since the Nuget creation and Nuget code signing are now done as two separate stages in the build pipeline, the Windows symbols publishing task fails as it relied on the `DownloadBuildArtifacts` tasks in the Nuget creation step. (This was missed in the refactoring of the pipeline in PR #93.)
However, since the Nuget doesn't contain any symbols at all, we can move the `DownloadBuildArtifacts` tasks entirely to the Nuget code signing stage instead.
Also, it turns out that the `PublishSymbols` task cannot run on the public Azure Pipelines pool and must be run on the PackageES pool. (Note: I skipped the actual publish step when testing PR #93, as you can't unpublish things once published. However, when running the Release Pipeline to publish for real, it errors out.)
Note: FWIW, the …
=> Fix Windows symbols publishing in the Nuget pipeline.

build/azure-nuget.yml
This merges the master branch to maint/maint-68 in order to pick up the fix for Windows symbols publishing (PR #98).
(This will be done as a merge commit to keep the history).
=> Update maint/maint-68 for fix for Windows symbols publishing

changelog.md, icu/icu4c/source/i18n/smpdtfmt.cpp
This cherry-picks the upstream fix to resolve the deadlock in `SimpleDateFormat::tzFormat`.
Upstream ticket: https://unicode-org.atlassian.net/browse/ICU-21591
Upstream PR: https://github.com/unicode-org/icu/pull/1701
=> Cherry-pick: ICU-21591 Release lock in SimpleDateFormat::tzFormat in case of failure

build/azure-pipelines.yml
This ports Jeff's fix from upstream ICU to work-around the Ubuntu 18.04 build bots from breaking the build pipelines when running the ICU tests.
Upstream fix: https://github.com/unicode-org/icu/pull/1723
=> Port work-around for Ubuntu 18.04 Azure CI built bot breaking builds

icu/icu4c/source/data/misc/windowsZones.txt
This updates the `windowsZones.txt` data file after cherry-picking the upstream CLDR changes to `windowsZones.xml` from here:
Upstream PR: https://github.com/unicode-org/cldr/pull/1193
CLDR ticket: https://unicode-org.atlassian.net/browse/CLDR-14653
=> Add South Sudan (Juba) to Windows time zone mapping

icu-patches/patches/019-ICU-Patch-ICU-21705_Fix_ures_openDirect_crash_with_NULL_localeID.patch, icu/icu4c/source/common/uresbund.cpp, icu/icu4c/source/test/cintltst/crestst.c
This PR fixes two issues:
- Fix crash if ICU's default locale has BCP47 Unicode Extensions.
- Fix `ures_openDirect` crash with a NULL input locale ID.
It also adds a test case for `ures_openDirect` with a NULL input locale ID.
This change adds a new ICU-PATCH file for the changes, though hopefully this won't be needed and we can fix this issue upstream before ingesting a new version of ICU.
*  **Note:** I've filed upstream tickets for these two issues and will be making a PR for them later.
Calling the public API `ures_openDirect` will crash if you call it with a `NULL` Locale ID -- even though this is permitted by the API docs.
The issue is that `strcmp` is called with the input locale ID (ie: null pointer), which is undefined behavior, and causes the crash.
This doesn't occur with …
=> Fix crash if ICU default locale has BCP47 extensions. Fix ures_openDirect crash with NULL locale.

build/azure-nuget.yml
This PR updates the build pool used for building the MS-ICU Nuget to migrate off the PackageES build agents and uses the public Microsoft hosted Azure DevOps build agents instead.
It also changes the publishing of the symbols for the MS-ICU Nuget, so that we can continue to have symbols available via the public MSDL symbol server.
The Package ES build agents are being deprecated, and will stop working after Sept 30th. This means that we need to move off of the `Package ES CodeHub Lab E` pool and find another pool to run our builds on.
Originally, I thought that we'd need to migrate to a custom hosted pool (using the 1ES Hosted Pool to run custom agents), but after doing some investigating, it turns out that we can actually run on the public Microsoft hosted Azure DevOps build agents …
=> Migrate from PackageES build agents to public Microsoft hosted Azure agents

changelog.md, icu/icu4c/source/common/unicode/uvernum.h, version.txt
This change bumps the version to 68.2.0.9, and updates the changelog.md file.
=> Bump version number to 68.2.0.9, and update changelog.md

changelog.md
When double-checking the content in `maint/maint-68`, I realized that I missed adding these entries to the `changelog.md` for `v68.2.0.9` in PR #114.
(FWIW, if you want to double-check, you can see the content here: https://github.com/microsoft/icu/pull/115/commits)
=> Add missing entries to changelog.md for v68.2.0.9

changelog.md, icu/icu4c/source/common/unicode/uvernum.h, version.txt
This change bumps the version to 68.2.0.10, and updates the changelog.md file.
=> Bump version number to 68.2.0.10 and update changelog

icu/tools/cldr/cldr-to-icu/pom.xml
This PR attempts to fix vulnerabilities found in the [CVE-2023-2976](https://nvd.nist.gov/vuln/detail/CVE-2023-2976). by updating the guava dependency version to 32.1.1 (latest available).
Note: An earlier automated PR also tried to do the same but it updates to 32.0.0 which has some issues on windows builds.
Thus, updating to latest version available
=> Update guava dependency to 32.1.1 (latest) to fix vulnerabilitites

icu/icu4c/source/data/brkitr/rules/word.txt, icu/icu4c/source/data/brkitr/rules/word_POSIX.txt, icu/icu4c/source/data/brkitr/rules/word_fi_sv.txt, icu/icu4c/source/test/intltest/rbbitst.cpp, icu/icu4c/source/test/testdata/break_rules/word.txt, icu/icu4c/source/test/testdata/rbbitst.txt
Cherry-picked from https://github.com/unicode-org/icu/pull/2460/files
The ICU 72 change to treat '@' as ALetter for word break could cause significant compatibility problems (for instance @-mentions in Twitter and other apps stopped working).
This reverts that change
=> Revert treatment of '@' as ALetter for word break

changelog.md, icu/icu4c/source/common/unicode/uvernum.h, version.txt
Updates the version number to ICU v 72.1.0.2
=> Update version number to 72.1.0.2

changelog.md, icu/icu4c/source/allinone/Build.Windows.ProjectConfiguration.props, icu/icu4c/source/common/unicode/uvernum.h, version.txt
We are disabling the plug-in loading capability for MS-ICU due to security concerns.
=> Disable the dynamic plug-in loading and update to v72.1.0.3

icu/icu4c/source/data/makedata_uwp.vcxproj
Adds a temporary workaround for a VS 17.12 issue that is affecting recently updated windows images of GitHub workflows and Azure pipelines. This should be removed after VS17.13 or later is installed in the images.
=> Workaround for issue with VS 17.12 in github/azure VMs

icu/icu4c/source/tools/ctestfw/tstdtmod.cpp, icu/icu4c/source/tools/makeconv/genmbcs.cpp, icu/icu4c/source/tools/pkgdata/pkgdata.cpp
Fix CodeQL issues and suppress a few non-production warnings
=> Address CodeQL issues affecting S360 items
